language: r

sudo: required

warnings_are_errors: true

cache: packages


apt_packages:
  - openjdk-8-jre
  - r-cran-rjava

before_install:
  - sudo $(which R) CMD javareconf


matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel


r_packages:
  - covr
  - rJava

r_github_packages: petermeissner/kafkaesquejars

after_success:
  - R -q -e 'library("covr");codecov()'

